name: Publish to NPM 🚀

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  NPN_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build WebApp Docker Image
        run: echo aaa
